import type { DeckSettings } from "./types";
import { createDefaultDeck, migrateDeck } from "./types";
const DRAFT_KEY = "deckforged:draft:v5"; const LEGACY_KEYS = ["deckforged:draft:v4", "deckforged:draft:v3", "deckforged:draft:v2"]; const DB_NAME = "deckforged-assets"; const STORE_NAME = "card-images";
export function loadDraft(): DeckSettings { if (typeof window === "undefined") return createDefaultDeck(); try { const raw = localStorage.getItem(DRAFT_KEY) || LEGACY_KEYS.map((key) => localStorage.getItem(key)).find(Boolean); return raw ? migrateDeck(JSON.parse(raw)) : createDefaultDeck(); } catch { return createDefaultDeck(); } }
export function saveDraft(deck: DeckSettings) { localStorage.setItem(DRAFT_KEY, JSON.stringify(deck)); }
export function clearDraft() { localStorage.removeItem(DRAFT_KEY); LEGACY_KEYS.forEach((key) => localStorage.removeItem(key)); }
function openDb(): Promise<IDBDatabase> { return new Promise((resolve, reject) => { const request = indexedDB.open(DB_NAME, 1); request.onupgradeneeded = () => request.result.createObjectStore(STORE_NAME); request.onsuccess = () => resolve(request.result); request.onerror = () => reject(request.error); }); }
export async function putImage(key: string, file: Blob) { const db = await openDb(); await new Promise<void>((resolve, reject) => { const tx = db.transaction(STORE_NAME, "readwrite"); tx.objectStore(STORE_NAME).put(file, key); tx.oncomplete = () => resolve(); tx.onerror = () => reject(tx.error); }); db.close(); }
export async function getImage(key: string): Promise<Blob | undefined> { const db = await openDb(); const value = await new Promise<Blob | undefined>((resolve, reject) => { const tx = db.transaction(STORE_NAME, "readonly"); const request = tx.objectStore(STORE_NAME).get(key); request.onsuccess = () => resolve(request.result as Blob | undefined); request.onerror = () => reject(request.error); }); db.close(); return value; }
export async function deleteImage(key: string) { const db = await openDb(); await new Promise<void>((resolve, reject) => { const tx = db.transaction(STORE_NAME, "readwrite"); tx.objectStore(STORE_NAME).delete(key); tx.oncomplete = () => resolve(); tx.onerror = () => reject(tx.error); }); db.close(); }
export async function clearImages() { const db = await openDb(); await new Promise<void>((resolve, reject) => { const tx = db.transaction(STORE_NAME, "readwrite"); tx.objectStore(STORE_NAME).clear(); tx.oncomplete = () => resolve(); tx.onerror = () => reject(tx.error); }); db.close(); }
