export type HistoricalCard = {
  date: string;
  title: string;
  maker: string;
  collection: string;
  image: string;
  source: string;
  provenance: string;
  significance: string;
};

export const HISTORICAL_CARDS: HistoricalCard[] = [
  { date: "ca. 1435–40", title: "The Queen of Flowers", maker: "Master of the Playing Cards", collection: "The Metropolitan Museum of Art, 2006.429", image: "https://collectionapi.metmuseum.org/api/collection/v1/iiif/373616/739681/main-image", source: "https://www.metmuseum.org/art/collection/search/373616", provenance: "German engraving printed from two plates. Acquired by The Met through the Janet Lee Kadesky Ruttenberg and Harris Brisbane Dick funds in 2006. The Met marks the image Public Domain.", significance: "This queen comes from the earliest substantial group of engraved playing cards. Its naturalistic flower suit predates the standardized French suits and shows how court ranks circulated through luxury printmaking." },
  { date: "ca. 1475–80", title: "King of Nooses", maker: "South Netherlandish artist", collection: "The Met Cloisters, 1983.515.40", image: "https://collectionapi.metmuseum.org/api/collection/v1/iiif/475565/1545285/main-image", source: "https://www.metmuseum.org/art/collection/search/475565", provenance: "One card from the only known complete fifteenth-century illuminated ordinary deck. Made in Burgundian territories on four-layer pasteboard with ink, opaque paint, glazes, silver, and gold. The Met marks the image Public Domain.", significance: "The deck's hunting-equipment suits and extravagant Burgundian clothing show that early European packs were local visual systems, not early versions of today's hearts, diamonds, clubs, and spades." },
  { date: "1810", title: "First French Empire King of Hearts", maker: "After Jacques-Louis David; drawn by Angélique Mongez; engraved by Bertrand Andrieu", collection: "Bibliothèque nationale de France, PET FOL-KH-34 (C, 28)", image: "https://commons.wikimedia.org/wiki/Special:Redirect/file/First%20French%20Empire%20card%20deck%20-%201810%20-%20King%20of%20Hearts.jpg?width=900", source: "https://commons.wikimedia.org/wiki/File:First_French_Empire_card_deck_-_1810_-_King_of_Hearts.jpg", provenance: "A Gallica scan of an engraved Paris deck preserved by the Bibliothèque nationale de France. Wikimedia Commons identifies the faithful reproduction and underlying work as public domain.", significance: "Revolutionary and Napoleonic governments repeatedly replaced the old royal figures. This Empire pack recasts court cards as approved historical and classical figures, making political authority visible at the card table." },
  { date: "1820–30", title: "Tudor and Oriental Court Pack", maker: "Unidentified British publisher", collection: "British Museum, 1896,0501.963", image: "https://upload.wikimedia.org/wikipedia/commons/7/7c/Print%2C_playing-card_%28BM_1896%2C0501.963%29.jpg", source: "https://commons.wikimedia.org/wiki/File:Print,_playing-card_(BM_1896,0501.963).jpg", provenance: "A hand-colored lithographed, single-ended pack of 51 surviving cards on pasteboard. The British Museum collection record traces the object; Wikimedia Commons identifies this mechanical scan as public domain.", significance: "The historical figures in three suits and orientalized diamond court show the nineteenth-century appetite for themed transformation packs. Court cards could carry narrative and costume while remaining playable." },
  { date: "mid-19th century", title: "Atlasnye Court-Card Studies", maker: "Adolf Charlemagne", collection: "Public-domain scan of the artist's Russian deck studies", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d5/%D0%90%D1%82%D0%BB%D0%B0%D1%81%D0%BD%D0%B0%D1%8F_%D0%BA%D0%BE%D0%BB%D0%BE%D0%B4%D0%B0_%D0%A8%D0%B0%D1%80%D0%BB%D0%B5%D0%BC%D0%B0%D0%BD%D1%8F._%D0%AD%D1%81%D0%BA%D0%B8%D0%B7%D1%8B.jpeg/500px-%D0%90%D1%82%D0%BB%D0%B0%D1%81%D0%BD%D0%B0%D1%8F_%D0%BA%D0%BE%D0%BB%D0%BE%D0%B4%D0%B0_%D0%A8%D0%B0%D1%80%D0%BB%D0%B5%D0%BC%D0%B0%D0%BD%D1%8F._%D0%AD%D1%81%D0%BA%D0%B8%D0%B7%D1%8B.jpeg", source: "https://commons.wikimedia.org/wiki/File:%D0%90%D1%82%D0%BB%D0%B0%D1%81%D0%BD%D0%B0%D1%8F_%D0%BA%D0%BE%D0%BB%D0%BE%D0%B4%D0%B0_%D0%A8%D0%B0%D1%80%D0%BB%D0%B5%D0%BC%D0%B0%D0%BD%D1%8F._%D0%AD%D1%81%D0%BA%D0%B8%D0%B7%D1%8B.jpeg", provenance: "Studies by Russian painter Adolf Charlemagne, who died in 1901. Commons identifies the scanned two-dimensional work as public domain and free of known restrictions in the United States.", significance: "Charlemagne's figures became the basis of the enduring Russian Atlasnye pattern. The studies reveal how drawing, simplification, and strong silhouettes turn court costume into legible mass-produced cards." },
  { date: "1888", title: "King of Spades, Duke Playing Cards", maker: "W. Duke, Sons & Co.", collection: "The Met, Jefferson R. Burdick Collection, 63.350.204.84.53", image: "https://collectionapi.metmuseum.org/api/collection/v1/iiif/424744/1871858/main-image", source: "https://www.metmuseum.org/art/collection/search/424744", provenance: "A commercial color lithograph issued in a 53-card cigarette-premium series. Gift of Jefferson R. Burdick to The Metropolitan Museum of Art. The Met marks the image Public Domain.", significance: "Industrial color printing let card imagery become advertising. The recognizable double-ended king remains playable while the deck itself promotes a national consumer brand, linking cards to modern mass media." },
];
