// ui/domRefs.js
export const dom = {
  canvas: document.getElementById('cardCanvas'),
  suitSelect: document.getElementById('suitSelect'),
  rankSelect: document.getElementById('rankSelect'),
  mirrorCardCheckbox: document.getElementById('mirrorCardCheckbox'),
  downloadCardButton: document.getElementById('downloadCardButton'),

  customRanksInput: document.getElementById('customRanksInput'),
  includeJokersCheckbox: document.getElementById('includeJokersCheckbox'),
  jokerCountInput: document.getElementById('jokerCountInput'),
  jokerLabelInput: document.getElementById('jokerLabelInput'),
  jokerWildCheckbox: document.getElementById('jokerWildCheckbox'),

  fontFamilyWrapper: document.getElementById('fontFamilyWrapper'),
  fontSizeInput: document.getElementById('fontSizeInput'),
  fontWeightSelect: document.getElementById('fontWeightSelect'),
  fontColorInput: document.getElementById('fontColorInput'),
  fontOpacityInput: document.getElementById('fontOpacityInput'),
  overlayTypeSelect: document.getElementById('overlayTypeSelect'),
  outlineCheckbox: document.getElementById('outlineCheckbox'),
  outlineWidthInput: document.getElementById('outlineWidthInput'),
  outlineColorInput: document.getElementById('outlineColorInput'),

  iconPresetSelect: document.getElementById('iconPresetSelect'),
  iconSheetInput: document.getElementById('iconSheetInput'),
  iconColorInput: document.getElementById('iconColorInput'),
  iconOpacityInput: document.getElementById('iconOpacityInput'),
  iconScaleInput: document.getElementById('iconScaleInput'),

  layoutButtons: document.getElementById('layoutButtons'),
  showPipsCheckbox: document.getElementById('showPipsCheckbox'),
  mirrorDefaultCheckbox: document.getElementById('mirrorDefaultCheckbox'),

  showGuidelinesCheckbox: document.getElementById('showGuidelinesCheckbox'),

  rankOffsetXInput: document.getElementById('rankOffsetXInput'),
  rankOffsetYInput: document.getElementById('rankOffsetYInput'),
  suitOffsetXInput: document.getElementById('suitOffsetXInput'),
  suitOffsetYInput: document.getElementById('suitOffsetYInput'),

  pipTopInput: document.getElementById('pipTopInput'),
  pipInnerTopInput: document.getElementById('pipInnerTopInput'),
  pipCenterInput: document.getElementById('pipCenterInput'),
  pipInnerBottomInput: document.getElementById('pipInnerBottomInput'),
  pipBottomInput: document.getElementById('pipBottomInput'),

  faceImageInput: document.getElementById('faceImageInput'),
  faceImageWrapper: document.getElementById('faceImageWrapper'),
  faceImageLabel: document.getElementById('faceImageLabel'),

  faceScaleInput: document.getElementById('faceScaleInput'),
  faceRotationInput: document.getElementById('faceRotationInput'),
  faceFlipHCheckbox: document.getElementById('faceFlipHCheckbox'),
  faceFlipVCheckbox: document.getElementById('faceFlipVCheckbox'),
  resetFaceTransformButton: document.getElementById('resetFaceTransformButton'),

  abilityMarkdownInput: document.getElementById('abilityMarkdownInput'),
  abilityPlacementSelect: document.getElementById('abilityPlacementSelect'),
  abilityMirrorCheckbox: document.getElementById('abilityMirrorCheckbox'),
  abilityAlignmentSelect: document.getElementById('abilityAlignmentSelect'),
  abilityWidthInput: document.getElementById('abilityWidthInput'),
  abilityHeightModeSelect: document.getElementById('abilityHeightModeSelect'),
  abilityFixedControls: document.getElementById('abilityFixedControls'),
  abilityFixedHeightInput: document.getElementById('abilityFixedHeightInput'),
  abilityOverflowSelect: document.getElementById('abilityOverflowSelect'),
  abilityBackgroundInput: document.getElementById('abilityBackgroundInput'),
  abilityBackgroundOpacityInput: document.getElementById('abilityBackgroundOpacityInput'),
  abilityHeaderFontWrapper: document.getElementById('abilityHeaderFontWrapper'),
  abilityHeaderFontLabel: document.getElementById('abilityHeaderFontLabel'),
  abilityBodyFontWrapper: document.getElementById('abilityBodyFontWrapper'),
  abilityBodyFontLabel: document.getElementById('abilityBodyFontLabel'),
  abilityHeaderFontSizeInput: document.getElementById('abilityHeaderFontSizeInput'),
  abilityBodyFontSizeInput: document.getElementById('abilityBodyFontSizeInput'),
  abilityHeaderFontWeightSelect: document.getElementById('abilityHeaderFontWeightSelect'),
  abilityBodyFontWeightSelect: document.getElementById('abilityBodyFontWeightSelect'),
  abilityTextColorInput: document.getElementById('abilityTextColorInput'),
  abilityTextOpacityInput: document.getElementById('abilityTextOpacityInput'),

  prevCardBtn: document.getElementById('prevCardBtn'),
  nextCardBtn: document.getElementById('nextCardBtn'),

  exportDeckButton: document.getElementById('exportDeckButton'),
  bulkUploadBadge: document.getElementById('bulkUploadBadge')
};
