// ui/domRefs.js
export const dom = {
  canvas: document.getElementById('cardCanvas'),
  suitSelect: document.getElementById('suitSelect'),
  rankSelect: document.getElementById('rankSelect'),
  mirrorCardCheckbox: document.getElementById('mirrorCardCheckbox'),
  downloadCardButton: document.getElementById('downloadCardButton'),

  customRanksInput: document.getElementById('customRanksInput'),
  includeJokersCheckbox: document.getElementById('includeJokersCheckbox'),
  jokerCountInput: document.getElementById('jokerCountInput'),
  jokerLabelInput: document.getElementById('jokerLabelInput'),
  jokerWildCheckbox: document.getElementById('jokerWildCheckbox'),
  jokerLabelOrientationSelect: document.getElementById('jokerLabelOrientationSelect'),
  jokerFontSizeInput: document.getElementById('jokerFontSizeInput'),
  jokerSuitStyleSelect: document.getElementById('jokerSuitStyleSelect'),

  fontFamilyWrapper: document.getElementById('fontFamilyWrapper'),
  fontSizeInput: document.getElementById('fontSizeInput'),
  fontWeightSelect: document.getElementById('fontWeightSelect'),
  fontColorModeSelect: document.getElementById('fontColorModeSelect'),
  fontColorInput: document.getElementById('fontColorInput'),
  fontColorEyedropper: document.getElementById('fontColorEyedropper'),
  fontColorBlackInput: document.getElementById('fontColorBlackInput'),
  fontColorBlackEyedropper: document.getElementById('fontColorBlackEyedropper'),
  fontColorRedInput: document.getElementById('fontColorRedInput'),
  fontColorRedEyedropper: document.getElementById('fontColorRedEyedropper'),
  fontColorSpadesInput: document.getElementById('fontColorSpadesInput'),
  fontColorSpadesEyedropper: document.getElementById('fontColorSpadesEyedropper'),
  fontColorHeartsInput: document.getElementById('fontColorHeartsInput'),
  fontColorHeartsEyedropper: document.getElementById('fontColorHeartsEyedropper'),
  fontColorClubsInput: document.getElementById('fontColorClubsInput'),
  fontColorClubsEyedropper: document.getElementById('fontColorClubsEyedropper'),
  fontColorDiamondsInput: document.getElementById('fontColorDiamondsInput'),
  fontColorDiamondsEyedropper: document.getElementById('fontColorDiamondsEyedropper'),
  fontSingleGroup: document.getElementById('fontSingleGroup'),
  fontBiColorGroup: document.getElementById('fontBiColorGroup'),
  fontPerSuitGroup: document.getElementById('fontPerSuitGroup'),
  fontOpacityInput: document.getElementById('fontOpacityInput'),
  overlayTypeSelect: document.getElementById('overlayTypeSelect'),
  outlineCheckbox: document.getElementById('outlineCheckbox'),
  outlineWidthInput: document.getElementById('outlineWidthInput'),
  outlineColorInput: document.getElementById('outlineColorInput'),

  iconPresetSelect: document.getElementById('iconPresetSelect'),
  iconSheetInput: document.getElementById('iconSheetInput'),
  iconColorModeSelect: document.getElementById('iconColorModeSelect'),
  iconColorInput: document.getElementById('iconColorInput'),
  iconColorEyedropper: document.getElementById('iconColorEyedropper'),
  iconColorBlackInput: document.getElementById('iconColorBlackInput'),
  iconColorBlackEyedropper: document.getElementById('iconColorBlackEyedropper'),
  iconColorRedInput: document.getElementById('iconColorRedInput'),
  iconColorRedEyedropper: document.getElementById('iconColorRedEyedropper'),
  iconColorSpadesInput: document.getElementById('iconColorSpadesInput'),
  iconColorSpadesEyedropper: document.getElementById('iconColorSpadesEyedropper'),
  iconColorHeartsInput: document.getElementById('iconColorHeartsInput'),
  iconColorHeartsEyedropper: document.getElementById('iconColorHeartsEyedropper'),
  iconColorClubsInput: document.getElementById('iconColorClubsInput'),
  iconColorClubsEyedropper: document.getElementById('iconColorClubsEyedropper'),
  iconColorDiamondsInput: document.getElementById('iconColorDiamondsInput'),
  iconColorDiamondsEyedropper: document.getElementById('iconColorDiamondsEyedropper'),
  iconSingleGroup: document.getElementById('iconSingleGroup'),
  iconBiColorGroup: document.getElementById('iconBiColorGroup'),
  iconPerSuitGroup: document.getElementById('iconPerSuitGroup'),
  iconOpacityInput: document.getElementById('iconOpacityInput'),
  iconScaleInput: document.getElementById('iconScaleInput'),

  layoutButtons: document.getElementById('layoutButtons'),
  showPipsCheckbox: document.getElementById('showPipsCheckbox'),
  mirrorDefaultCheckbox: document.getElementById('mirrorDefaultCheckbox'),
  backgroundStyleSelect: document.getElementById('backgroundStyleSelect'),
  backgroundPrimaryInput: document.getElementById('backgroundPrimaryInput'),
  backgroundPrimaryEyedropper: document.getElementById('backgroundPrimaryEyedropper'),
  backgroundSecondaryInput: document.getElementById('backgroundSecondaryInput'),
  backgroundSecondaryEyedropper: document.getElementById('backgroundSecondaryEyedropper'),
  backgroundSecondaryGroup: document.getElementById('backgroundSecondaryGroup'),

  showGuidelinesCheckbox: document.getElementById('showGuidelinesCheckbox'),

  rankOffsetXInput: document.getElementById('rankOffsetXInput'),
  rankOffsetYInput: document.getElementById('rankOffsetYInput'),
  suitOffsetXInput: document.getElementById('suitOffsetXInput'),
  suitOffsetYInput: document.getElementById('suitOffsetYInput'),

  pipTopInput: document.getElementById('pipTopInput'),
  pipInnerTopInput: document.getElementById('pipInnerTopInput'),
  pipCenterInput: document.getElementById('pipCenterInput'),
  pipInnerBottomInput: document.getElementById('pipInnerBottomInput'),
  pipBottomInput: document.getElementById('pipBottomInput'),
  pipTopValue: document.getElementById('pipTopValue'),
  pipInnerTopValue: document.getElementById('pipInnerTopValue'),
  pipCenterValue: document.getElementById('pipCenterValue'),
  pipInnerBottomValue: document.getElementById('pipInnerBottomValue'),
  pipBottomValue: document.getElementById('pipBottomValue'),

  faceImageInput: document.getElementById('faceImageInput'),
  faceImageWrapper: document.getElementById('faceImageWrapper'),
  faceImageLabel: document.getElementById('faceImageLabel'),

  faceScaleInput: document.getElementById('faceScaleInput'),
  faceRotationInput: document.getElementById('faceRotationInput'),
  faceFlipHCheckbox: document.getElementById('faceFlipHCheckbox'),
  faceFlipVCheckbox: document.getElementById('faceFlipVCheckbox'),
  resetFaceTransformButton: document.getElementById('resetFaceTransformButton'),

  resetFontsButton: document.getElementById('resetFontsButton'),
  resetIconsButton: document.getElementById('resetIconsButton'),
  resetBackgroundButton: document.getElementById('resetBackgroundButton'),
  resetLayoutButton: document.getElementById('resetLayoutButton'),
  resetPipPositionsButton: document.getElementById('resetPipPositionsButton'),
  resetCornersButton: document.getElementById('resetCornersButton'),
  resetAbilityButton: document.getElementById('resetAbilityButton'),
  resetDeckButton: document.getElementById('resetDeckButton'),
  fullResetButton: document.getElementById('fullResetButton'),
  confirmFullResetButton: document.getElementById('confirmFullResetButton'),
  cancelFullResetButton: document.getElementById('cancelFullResetButton'),
  fullResetModal: document.getElementById('fullResetModal'),

  linkPipOuterButton: document.getElementById('linkPipOuterButton'),
  linkPipInnerButton: document.getElementById('linkPipInnerButton'),
  linkPipCenterButton: document.getElementById('linkPipCenterButton'),

  abilityMarkdownInput: document.getElementById('abilityMarkdownInput'),
  abilityPlacementSelect: document.getElementById('abilityPlacementSelect'),
  abilityMirrorCheckbox: document.getElementById('abilityMirrorCheckbox'),
  abilityAlignmentSelect: document.getElementById('abilityAlignmentSelect'),
  abilityWidthInput: document.getElementById('abilityWidthInput'),
  abilityHeightModeSelect: document.getElementById('abilityHeightModeSelect'),
  abilityFixedControls: document.getElementById('abilityFixedControls'),
  abilityFixedHeightInput: document.getElementById('abilityFixedHeightInput'),
  abilityOverflowSelect: document.getElementById('abilityOverflowSelect'),
  abilityBackgroundInput: document.getElementById('abilityBackgroundInput'),
  abilityBackgroundOpacityInput: document.getElementById('abilityBackgroundOpacityInput'),
  abilityHeaderFontWrapper: document.getElementById('abilityHeaderFontWrapper'),
  abilityHeaderFontLabel: document.getElementById('abilityHeaderFontLabel'),
  abilityBodyFontWrapper: document.getElementById('abilityBodyFontWrapper'),
  abilityBodyFontLabel: document.getElementById('abilityBodyFontLabel'),
  abilityHeaderFontSizeInput: document.getElementById('abilityHeaderFontSizeInput'),
  abilityBodyFontSizeInput: document.getElementById('abilityBodyFontSizeInput'),
  abilityHeaderFontWeightSelect: document.getElementById('abilityHeaderFontWeightSelect'),
  abilityBodyFontWeightSelect: document.getElementById('abilityBodyFontWeightSelect'),
  abilityTextColorInput: document.getElementById('abilityTextColorInput'),
  abilityTextOpacityInput: document.getElementById('abilityTextOpacityInput'),

  prevCardBtn: document.getElementById('prevCardBtn'),
  nextCardBtn: document.getElementById('nextCardBtn'),

  exportDeckButton: document.getElementById('exportDeckButton'),
  bulkUploadBadge: document.getElementById('bulkUploadBadge')
};
